# Generated by Django 3.2.7 on 2021-10-07 09:30

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpriseContactInformatiom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('facebook_account', models.URLField(blank=True, max_length=254, null=True)),
                ('linkedin_account', models.URLField(blank=True, max_length=254, null=True)),
                ('twiter_account', models.URLField(blank=True, max_length=254, null=True)),
                ('instagram_account', models.URLField(blank=True, max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Interprise contact information',
                'verbose_name_plural': 'Interprise contact informations',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, max_length=254, null=True)),
                ('profile_image', models.ImageField(default='default.png', upload_to='testimonials-images/%Y/%m/%d/')),
                ('phone_number', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('team_membre_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('facebook_account', models.URLField(blank=True, max_length=254, null=True)),
                ('linkedin_account', models.URLField(blank=True, max_length=254, null=True)),
                ('twiter_account', models.URLField(blank=True, max_length=254, null=True)),
                ('instagram_account', models.URLField(blank=True, max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team member',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone_number', models.CharField(blank=True, max_length=254, null=True)),
                ('user_address', models.CharField(blank=True, max_length=254, null=True)),
                ('profile_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('user_profile_pic', models.ImageField(default='default.png', upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'Users Accounts',
            },
        ),
        migrations.CreateModel(
            name='TeamMemberSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=254, null=True)),
                ('skill_level', models.IntegerField(blank=True, null=True)),
                ('skill_detail', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
                ('assign_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interprise.teammember')),
            ],
            options={
                'verbose_name': 'Team member skill',
                'verbose_name_plural': 'Team Members skills',
            },
        ),
    ]
