# Generated by Django 3.2.7 on 2021-10-07 09:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import fontawesome_5.fields
import osm_field.fields
import osm_field.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Base page',
                'verbose_name_plural': 'Base pages',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=254, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=254, null=True)),
                ('object', models.CharField(max_length=254, null=True)),
                ('message', models.TextField(max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact us form',
                'verbose_name_plural': 'Contact us forms',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=254, null=True)),
                ('map_latitud', models.IntegerField(blank=True, null=True)),
                ('map_longitud', models.IntegerField(blank=True, null=True)),
                ('country_flag', models.ImageField(default='default.png', upload_to='countries-flags/%Y/%m/%d/')),
                ('country_image', models.ImageField(default='default.png', upload_to='countries-images/%Y/%m/%d/')),
                ('country_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
                ('base_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.basepage')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Dicipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicipline_name', models.CharField(help_text='Enter the dicipline name :Ex Medecine & Health', max_length=254, null=True)),
                ('short_name', models.CharField(max_length=254, null=True)),
                ('dicipline_icon', fontawesome_5.fields.IconField(blank=True, max_length=60, null=True)),
                ('dicipline_image', models.ImageField(default='default', upload_to='dicipline-images/%Y/%m/%d/')),
                ('simple_description', models.TextField(help_text='Simple description for this dicipline in maximum of 500 letters', max_length=400, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
                ('set_featured', models.BooleanField(default=False)),
                ('base_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.basepage')),
            ],
            options={
                'verbose_name': 'Dicipline',
                'verbose_name_plural': 'Diciplines',
            },
        ),
        migrations.CreateModel(
            name='DiciplineTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dicipline tag',
                'verbose_name_plural': 'Dicipline tags',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
                ('set_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality_name', models.CharField(max_length=254, null=True)),
                ('speciality_description', ckeditor.fields.RichTextField(null=True)),
                ('year_of_study', models.CharField(max_length=254, null=True)),
                ('average_fees', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
                ('set_featured', models.BooleanField(default=False)),
                ('dicipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.dicipline')),
                ('study_level', models.ManyToManyField(to='main.DiciplineTag')),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(blank=True, max_length=254, null=True)),
                ('region', models.CharField(blank=True, max_length=254, null=True)),
                ('university_logo', models.ImageField(default='default.png', upload_to='universities-logo/%Y/%m/%d/')),
                ('university_image', models.ImageField(default='default.png', upload_to='universities-images/%Y/%m/%d/')),
                ('university_description', models.TextField(blank=True, help_text='Describe this university in maxumun of 700', max_length=700, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
                ('location', osm_field.fields.OSMField(blank=True, lat_field='location_lat', lon_field='location_lon', null=True)),
                ('location_lat', osm_field.fields.LatitudeField(blank=True, null=True, validators=[osm_field.validators.validate_latitude])),
                ('location_lon', osm_field.fields.LongitudeField(blank=True, null=True, validators=[osm_field.validators.validate_longitude])),
                ('base_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.basepage')),
                ('choose_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.country')),
                ('university_specialities', models.ManyToManyField(to='main.Speciality')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='UniversityFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_name', models.CharField(blank=True, max_length=254, null=True)),
                ('fact_description', models.TextField(blank=True, max_length=254, null=True)),
                ('fact_icon', fontawesome_5.fields.IconField(blank=True, max_length=60, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
                ('chose_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.university')),
            ],
            options={
                'verbose_name': 'University fact',
                'verbose_name_plural': 'Universities Fact',
            },
        ),
        migrations.CreateModel(
            name='ProgramFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_name', models.CharField(blank=True, max_length=254, null=True)),
                ('fact_description', models.TextField(blank=True, max_length=40, null=True)),
                ('fact_icon', fontawesome_5.fields.IconField(blank=True, max_length=60, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
                ('chose_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.program')),
            ],
            options={
                'verbose_name': 'Program fact',
                'verbose_name_plural': 'Programs Fact',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='choose_university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.university'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.speciality'),
        ),
        migrations.CreateModel(
            name='CountryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_name', models.CharField(blank=True, max_length=254, null=True)),
                ('fact_description', models.TextField(blank=True, max_length=254, null=True)),
                ('fact_icon', fontawesome_5.fields.IconField(blank=True, max_length=60, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
                ('chose_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.country')),
            ],
            options={
                'verbose_name': 'Country fact',
                'verbose_name_plural': 'Countries Fact',
            },
        ),
    ]
