# Generated by Django 3.2.7 on 2021-10-07 09:53

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='base_page',
            field=models.ForeignKey(blank=True, default=main.models.get_continent, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.basepage'),
        ),
        migrations.AlterField(
            model_name='dicipline',
            name='base_page',
            field=models.ForeignKey(blank=True, default=main.models.get_dicipline, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.basepage'),
        ),
        migrations.AlterField(
            model_name='university',
            name='base_page',
            field=models.ForeignKey(blank=True, default=main.models.get_university, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.basepage'),
        ),
    ]
