# Generated by Django 3.2.7 on 2021-09-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_name', models.CharField(blank=True, max_length=254, null=True)),
                ('fact_description', models.TextField(blank=True, max_length=254, null=True)),
                ('fact_icon', models.CharField(blank=True, max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'University fact',
                'verbose_name_plural': 'Universities Fact',
            },
        ),
    ]
