# Generated by Django 3.2.7 on 2021-10-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211007_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='base_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.basepage'),
        ),
    ]
