# Generated by Django 3.2.7 on 2021-09-10 04:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_universityfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(blank=True, max_length=254, null=True)),
                ('university_image', models.ImageField(default='default.png', upload_to='')),
                ('university_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('university_fact', models.ManyToManyField(blank=True, to='main.UniversityFact')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
    ]
