# Generated by Django 3.2.7 on 2021-10-07 10:19

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_speciality_base_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='base_page',
            field=models.ForeignKey(blank=True, default=main.models.get_specialty, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.basepage'),
        ),
    ]
