# Generated by Django 3.2.7 on 2021-09-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
