# Generated by Django 3.2.7 on 2021-10-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_speciality_base_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='study_level',
            field=models.ManyToManyField(to='main.DiciplineTag'),
        ),
    ]
