# Generated by Django 3.2.7 on 2021-10-11 03:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_program_study_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepage',
            name='page_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='object',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_flag',
            field=models.ImageField(blank=True, default='default.png', upload_to='countries-flags/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_image',
            field=models.ImageField(blank=True, default='default.png', upload_to='countries-images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='dicipline',
            name='dicipline_image',
            field=models.ImageField(blank=True, default='default', upload_to='dicipline-images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='dicipline',
            name='dicipline_name',
            field=models.CharField(blank=True, help_text='Enter the dicipline name :Ex Medecine & Health', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dicipline',
            name='simple_description',
            field=models.TextField(blank=True, help_text='Simple description for this dicipline in maximum of 500 letters', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='diciplinetag',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='choose_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.university'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.speciality'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='dicipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.dicipline'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='speciality_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='speciality_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='study_level',
            field=models.ManyToManyField(blank=True, to='main.DiciplineTag'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='choose_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.country'),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_image',
            field=models.ImageField(blank=True, default='default.png', upload_to='universities-images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_logo',
            field=models.ImageField(blank=True, default='default.png', upload_to='universities-logo/%Y/%m/%d/'),
        ),
    ]
