# Generated by Django 3.2.7 on 2021-09-10 12:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210910_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Post Category', 'verbose_name_plural': 'Post Categories'},
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=254, null=True)),
                ('map_latitud', models.IntegerField(blank=True, null=True)),
                ('map_longitud', models.IntegerField(blank=True, null=True)),
                ('country_image', models.ImageField(default='default.png', upload_to='')),
                ('country_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('university_in_country', models.ManyToManyField(blank=True, to='main.University')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
