# Generated by Django 3.2.7 on 2021-10-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211011_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='select_continent',
            field=models.CharField(blank=True, choices=[('Asia', 'Asia'), ('Africa', 'Africa'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Oceania', 'Oceania')], max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dicipline',
            name='short_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_specialities',
            field=models.ManyToManyField(blank=True, to='main.Speciality'),
        ),
    ]
