# Generated by Django 3.2.7 on 2021-09-10 13:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210910_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, max_length=254, null=True)),
                ('profile_image', models.ImageField(default='default.png', upload_to='')),
                ('phone_number', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('team_membre_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('facebook_account', models.URLField(blank=True, max_length=254, null=True)),
                ('linkedin_account', models.URLField(blank=True, max_length=254, null=True)),
                ('twiter_account', models.URLField(blank=True, max_length=254, null=True)),
                ('instagram_account', models.URLField(blank=True, max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team member',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='set_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='set_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='set_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='set_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postreview',
            name='set_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='set_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='university',
            name='set_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='universityfact',
            name='set_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='set_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='TeamMemberSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=254, null=True)),
                ('skill_level', models.IntegerField(blank=True, null=True)),
                ('skill_detail', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
                ('assign_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.teammember')),
            ],
            options={
                'verbose_name': 'Team member skill',
                'verbose_name_plural': 'Team Members skills',
            },
        ),
    ]
