# Generated by Django 3.2.7 on 2021-09-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210910_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpriseContactInformatiom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('facebook_account', models.URLField(blank=True, max_length=254, null=True)),
                ('linkedin_account', models.URLField(blank=True, max_length=254, null=True)),
                ('twiter_account', models.URLField(blank=True, max_length=254, null=True)),
                ('instagram_account', models.URLField(blank=True, max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Interprise contact information',
                'verbose_name_plural': 'Interprise contact informations',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_by', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('commment', models.TextField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
                ('blog_post', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.blogpost')),
            ],
            options={
                'verbose_name': 'Post comment',
                'verbose_name_plural': 'Post Comments',
            },
        ),
        migrations.DeleteModel(
            name='PostReview',
        ),
    ]
