# Generated by Django 3.2.7 on 2021-09-10 14:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210910_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_category_title', models.CharField(blank=True, max_length=254, null=True)),
                ('program_category_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('program_category_image', models.ImageField(default='default', upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('set_draft', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Program Category',
                'verbose_name_plural': 'Program Categories',
            },
        ),
        migrations.RenameModel(
            old_name='Pages',
            new_name='Program',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='page_description',
            new_name='program_description',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='page_image',
            new_name='program_image',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='page_name',
            new_name='program_name',
        ),
    ]
