# Generated by Django 3.2.7 on 2021-09-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210912_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='realted_university',
            new_name='choose_university',
        ),
    ]
