# Generated by Django 3.2.7 on 2021-09-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_program_program_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_category',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_category',
            field=models.ManyToManyField(blank=True, to='main.PostCategory'),
        ),
    ]
