# Generated by Django 3.2.7 on 2021-09-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210913_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='program_category',
        ),
        migrations.AddField(
            model_name='program',
            name='program_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.programcategory'),
        ),
    ]
