# Generated by Django 3.2.7 on 2021-09-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210913_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcategory',
            name='set_featured',
            field=models.BooleanField(default=False),
        ),
    ]
