# Generated by Django 3.2.7 on 2021-09-14 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_programcategory_set_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='choose_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.university'),
        ),
    ]
