# Generated by Django 3.2.7 on 2021-09-14 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_program_choose_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programfact',
            name='chose_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.program'),
        ),
    ]
