# Generated by Django 3.2.7 on 2021-09-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_programfact_chose_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programfact',
            name='fact_description',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
    ]
