# Generated by Django 3.2.7 on 2021-09-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_programfact_fact_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_flag',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
