# Generated by Django 3.2.7 on 2021-09-14 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_country_country_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryfact',
            name='chose_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.country'),
        ),
    ]
