# Generated by Django 3.2.7 on 2021-09-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210914_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='university_logo',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
