# Generated by Django 3.2.7 on 2021-09-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_university_university_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='pOst_category_image',
            new_name='post_category_image',
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='post_category_description',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
    ]
