# Generated by Django 3.2.7 on 2021-09-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210916_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='psot_description',
            new_name='post_description',
        ),
    ]
