# Generated by Django 3.2.7 on 2021-09-16 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_psot_description_blogpost_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.blogpost'),
        ),
    ]
