# Generated by Django 3.2.7 on 2021-09-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rename_commment_postcomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.blogpost'),
        ),
    ]
