# Generated by Django 3.2.7 on 2021-09-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_postcomment_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='set_featured',
            field=models.BooleanField(default=True),
        ),
    ]
