# Generated by Django 3.2.7 on 2021-09-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_blogpost_set_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_icon',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
