# Generated by Django 3.2.7 on 2021-09-19 07:16

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_program_program_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60, null=True),
        ),
    ]
