# Generated by Django 3.2.7 on 2021-09-20 07:47

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_program_program_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryfact',
            name='fact_icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='programfact',
            name='fact_icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='universityfact',
            name='fact_icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60, null=True),
        ),
    ]
