# Generated by Django 3.2.7 on 2021-09-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20210920_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_short_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
