# Generated by Django 3.2.7 on 2021-09-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='object',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
