# Generated by Django 3.2.7 on 2021-09-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('last_mame', models.CharField(blank=True, max_length=254, null=True)),
                ('nationality', models.CharField(blank=True, max_length=254, null=True)),
                ('country_of_residence', models.CharField(blank=True, max_length=254, null=True)),
                ('emial', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=254, null=True)),
                ('graduation_year', models.DateField(blank=True, null=True)),
                ('course_of_interest', models.CharField(blank=True, max_length=254, null=True)),
                ('educational_qualification', models.CharField(blank=True, max_length=254, null=True)),
                ('additinal_infoemation', models.TextField(blank=True, max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact us form',
                'verbose_name_plural': 'Contact us forms',
            },
        ),
        migrations.CreateModel(
            name='GetIntouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('last_mame', models.CharField(blank=True, max_length=254, null=True)),
                ('nationality', models.CharField(blank=True, max_length=254, null=True)),
                ('emial', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=254, null=True)),
                ('graduation_year', models.DateField(blank=True, null=True)),
                ('course_of_interest', models.CharField(blank=True, max_length=254, null=True)),
                ('educational_qualification', models.CharField(blank=True, max_length=254, null=True)),
                ('additinal_infoemation', models.TextField(blank=True, max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Get in touch',
                'verbose_name_plural': 'Get in touchs',
            },
        ),
    ]
