# Generated by Django 3.2.7 on 2021-10-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, help_text='Your Name', max_length=254, null=True),
        ),
    ]
