# Generated by Django 3.2.7 on 2021-09-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0003_auto_20210922_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='object',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
