# Generated by Django 3.2.7 on 2021-09-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0004_contactus_object'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
