# Generated by Django 3.2.7 on 2021-09-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0005_delete_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='getintouch',
            name='program_cateory',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='educational_qualification',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
    ]
