# Generated by Django 3.2.7 on 2021-09-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0006_auto_20210928_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='getintouch',
            name='country',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
