# Generated by Django 3.2.7 on 2021-09-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0007_getintouch_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getintouch',
            old_name='last_mame',
            new_name='last_name',
        ),
    ]
